# Generated by Django 4.2.29 on 2026-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("action_type", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("favorite_categories", models.JSONField(default=list)),
                ("favorite_brands", models.JSONField(default=list)),
                ("average_price_bucket", models.IntegerField(default=1)),
            ],
        ),
    ]
