# Generated by Django 4.2.29 on 2026-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="products_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
